### PR TITLE
prevent withMutations from setting values on non defined record keys

### LINKED ISSUE #79: Record.withMutations adds extraneous keys
*From @alessandrotilli on Fri, 08 Jun 2018 08:59:08 GMT*

From the docs:

> A record is similar to a JS object, but enforces a specific set of allowed string keys

Using `withMutations` to modify a record can break the previous statement, allowing you to add extraneous keys. 

### How to reproduce

```javascript
const { Record } = require('immutable');

const Rec = new Record({ a: 1 });
const rec = new Rec();

const r1 = rec.set('wtf', '?');
console.log(r1.wtf); // undefined (OK)

const r2 = rec.withMutations((m) => {
  m.a = 2;
  m.wtf = '?';
})

console.log(r2.a); // 2
console.log(r2.wtf); // ? (unexpected)
console.log(r2.has('wtf')) // false;
```
tested on immutable@4.0.0-rc.9.

The same behaviour occurs with immutable@3.8.2, the only difference is that `rec.set('wtf', '?')` (correctly) throws an error.

*Copied from original issue: https://github.com/immutable-js/immutable-js/issues/1542*

### PR DESCRIPTION
**Pull request by jdeniau**
A PR was present on immutable-js original repository by @Brantron in https://github.com/immutable-js/immutable-js/issues/1544. I just cherry-picked the commit. 

It is compatible with IE9+.

Fixes #79

### CODE REVIEW

**Comment by Methuselah96** [comment]
Part of the issue also seemed to be that `const r1 = rec.set('wtf', '?');` should throw an error, but it doesn't, which this PR doesn't fix. Maybe I'm reading that incorrectly?

**Comment by jdeniau** [comment]
@Methuselah96 according to [this test](https://github.com/immutable-js-oss/immutable-js/blob/master/__tests__/Record.ts#L49-L56), this has been changed from "throwing an error" to "do nothing".

Both `set` and `withMultation + set` now have the same comportment. It looks to me that this is fixed

**Comment by jdeniau** [comment]
Superseeded by https://github.com/immutable-js/immutable-js/pull/1837

**Comment by jdeniau** [comment]
Superseeded by the original PR : https://github.com/immutable-js/immutable-js/pull/1544

**Pull request closed without merging**
