### PR TITLE
[typescript] Map constructor now accept a list of keys in the object notation

### PR DESCRIPTION
**Pull request by jdeniau**
The typescript definition of Map does accept a `Key` only for the array construction syntax.

This way:

```ts
const a = Map<'status' | 'foo', string | null>([['status', 'paid']]); // OK
const a1 = a.get('status'); // OK
const a2 = a.get('unknow-key'); // report error (OK)
const a = Map<'status' | 'foo', string | null>([['status', 'paid'], ['unwanted-key', 'test']]); // report error (OK)
```

But if we use the object notation, the error reporting is wrong

```ts
const b = Map<'status' | 'foo', string | null>({
  status: 'paid', // report wrongly "Argument of type '{ status: string; }' is not assignable to parameter of type 'Iterable<["status" | "foo", string | null]>'"
});
const b1 = a.get('status'); // OK
const b2 = a.get('unknow-key'); // report error (OK)
```

With this change, the object notation now works as expected

```ts
const b = Map<'status' | 'foo', string | null>({
  status: 'paid', // OK
});
const b1 = a.get('status'); // OK
const b2 = a.get('unknow-key'); // report error (OK)
Map<'status' | 'foo', string | null>({ // throws "Argument of type '{ status: string; bar: string; }' is not assignable to parameter of type '{ status?: string | null | undefined; foo?: string | null | undefined; }'." (OK)
  status:  'paid',
  bar: 'baz',
})
```

### CODE REVIEW

**Comment by jdeniau** [comment]
Ping @conartist6 @Methuselah96 as you both worked on this file ?

**Comment by conartist6** [comment]
I will argue strongly against this change. The authors of the es6 specification had every opportunity to make the language work this way and they did not. Following the lead of the language is one reason not to do this. Second, it should be very easy to work around the lack of support. Just provide a function that iterates over the keys of an object. `iter-tools` provides `objectEntries`, and Immutable could provide something similar. I think it's fine to expect the user to do a little extra work in order to avoid painting ourselves into a corner.

**Comment by conartist6** [comment]
OH this already works doesn't it >_<. It just isn't typed well enough...

**Comment by jdeniau** [comment]
@conartist6 the issue is only with typescript definition yes. The definition works if you a list of list `Map([['status', 'paid']])` but not with the object notation `Map({status: 'paid'})` (which is the primary feature for me, and I think I am not alone).

I tried to copy what is working with `Record` : [example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAysCGwCuBnAShAxgewE4BMoBeKDHAgHgHIUFkUqAfKgM22yoBopbcBLAHYBzAHwBuAFAScA2jwBcsOqjJ5CJAN4SoPZSkVUw8Pvi7aobbActmAvlJkpsAGwgA6Z9iEAKFG5QAFthIzvgAKgG42ADuAJSS0tiywDxBIeGRMQBMinCIKlhqxFBaOrT5+lCGxqac5gBG8LgGjbhUUHW2QA)

**Comment by EricTheRed-VT** [comment]
This would be really nice to have type support for, the code already runs and tuple arrays are fairly annoying.

@jdeniau Would your fix also work with simple/non-union key types, e.g. `Map<number, string>({3: "foo"})` or `Map<symbol, () => void>({[mySymbol]: clickHandler})`? Even `Map<string, unknown>({a: 1})` isn't supported right now, although obviously you can just use `Map<unknown>({a: 1})` in that case.

**Comment by jdeniau** [comment]
@cypherfunc I think it should already work due to this following rules:

```
  export function Map<K, V>(): Map<K, V>;
  export function Map<K, V>(collection: Iterable<[K, V]>): Map<K, V>;
```

It my not work in 3.8.2 though as the 3.8.2 `.d.ts` file is old and broken IIRC.

**Comment by jdeniau** [comment]
Superseeded by https://github.com/immutable-js/immutable-js/pull/1837

**Pull request closed without merging**
