### PR TITLE
Migrate gulp 3 to 4

### PR DESCRIPTION
**Pull request by hahnlee**
- Migrate gulp 3 to 4
- Support Node.js 10+

### CODE REVIEW

**Comment by hahnlee** [comment]
Related https://github.com/immutable-js/immutable-js/pull/1768

Test on macOS
- v10.22.0
- v12.18.3
- v13.10.1

**Comment by Methuselah96** [comment]
@hahnlee It doesn't look like `pages/generated/readme.json` and `pages/generated/immutable.d.json` are getting written out like they should be which is why the build is failing. Can you look into that?

**Comment by hahnlee** [comment]
@Methuselah96 🆗

**Comment by hahnlee** [comment]
@Methuselah96 Fixed :D

**Comment by Methuselah96** [comment]
Thanks!

**Pull request merged**
