### PR TITLE
Allow running tests without building dist + lines are correcly reported now

### LINKED ISSUE #202: [DX] run test on non-builded codebase
I open this issue as for a first time contributor I ran into some bumps on the road :

To run tests, I have to "build" the project, as apparently the test run on the compiled version of the code.

Otherwise, if you clone a fresh project and run `yarn install && yarn test` it does throw an exception about missing files.

One more "issue" with that is that the stacktrace in the test suite reports incorrect files and line numbers.

So my question here is that :

- do I use it "the wrong way"? 
- is this a "feature" / is this needed?

### PR DESCRIPTION
**Pull request by jdeniau**
Fixes #202 

The tests does not need to be ran on a builded version of immutable. This improves the DX:

- obviously, no need to build immutable when the code changes
- `--watch` options does work now
- the reported line in the tests files AND in the code files are reported correctly (see below)

#### if test is failing 

Before :
```
  ● Record › defines a constructor

    expect(received).toBe(expected) // Object.is equality

    Expected: "this should the integer 10"
    Received: 10

      19 |     expect(t1 instanceof Record).toBe(true);
      20 |     expect(t1 instanceof MyType).toBe(true);
    > 21 | 
         | ^
      22 |     expect(t2 instanceof Record).toBe(true);
      23 |     expect(t2 instanceof MyType).toBe(true);
      24 | 

      at Object.<anonymous> (__tests__/Record.ts:21:29)
```

Now : 
```
  ● Record › defines a constructor

    expect(received).toBe(expected) // Object.is equality

    Expected: "this should the integer 10"
    Received: 10

      24 | 
      25 |     expect(t1.get('a')).toBe(1);
    > 26 |     expect(t2.get('a')).toBe('this should the integer 10');
         |                         ^
      27 |   });
      28 | 
      29 |   it('allows for a descriptive name', () => {

      at Object.<anonymous> (__tests__/Record.ts:26:25)
```

#### if somethings happens in the code (let's say an error is thrown)

Before:
```
  ● Record › falls back to default values when deleted or cleared

    test get

      5565 | 
      5566 |   Record.prototype.clear = function clear () {
    > 5567 |     throw new Error('test get');
           |           ^
      5568 |     var newValues = this._values.clear().setSize(this._keys.length);
      5569 |     return this.__ownerID ? this : makeRecord(this, newValues);
      5570 |   };

      at Record.clear (dist/immutable.js:5567:11)
      at Object.<anonymous> (__tests__/Record.ts:51:23)
```

Now:
```
  ● Record › falls back to default values when deleted or cleared

    test get

      152 | 
      153 |   clear() {
    > 154 |     throw new Error('test get');
          |           ^
      155 |     const newValues = this._values.clear().setSize(this._keys.length);
      156 |     return this.__ownerID ? this : makeRecord(this, newValues);
      157 |   }

      at Record.clear (src/Record.js:154:11)
      at Object.<anonymous> (__tests__/Record.ts:63:19)
```

There is only one file that can not be converted : [MultiRequire](https://github.com/immutable-js-oss/immutable-js/blob/master/__tests__/MultiRequire.js#L16) as now two imports are the same instance 🤔

### CODE REVIEW

**Comment by conartist6** [comment]
Let's change the imports to be from the package name instead of from the `src` folder. I've just done this with my project and it worked great -- that way I am able to test the sources or the dist code just by changing the way the package name resolves. CI should test the dist code, and local devs should test the src code.

Node already supports self-references in requires and jest [wants to do so in their next major release](https://github.com/browserify/resolve/pull/224#issuecomment-739891844). In the mean time I wrote a [babel plugin](https://gist.github.com/conartist6/214e663b3b2fc99ca3be488e0f205010) that simulates the functionality.

**Comment by conartist6** [comment]
I guess I should publish that plugin huh.

**Comment by jdeniau** [comment]
@conartist6 immutable does not use babel but [buble](https://github.com/immutable-js-oss/immutable-js/blob/master/resources/rollup-config.js#L36) in its build system.

If jest does allow self-referencing in it's next major version, I suggest to wait that they do and then replace all links from `'../src/Immutable'` to `'immutable'`, but this can be done in a future release without problem.

**Comment by conartist6** [comment]
buble -__-

Just make sure there's some way to test the product we actually ship. I don't really care how hacky it is.

**Comment by jdeniau** [comment]
@conartist6 @Methuselah96 the solution was in fact quite simple: 
I added the [jestResolver.js](https://github.com/immutable-js-oss/immutable-js/pull/205/files#diff-521b5aa88eace2c64dff7195cae81955a21cda6dacca0716dbf1cc4b0c6c0245) file, a [jest resolver](https://jestjs.io/docs/en/configuration.html#resolver-string) that catches imports from "immutable".

If we are on CI, it will resolve to package.json "main" entry, else on `src/Immutable.js`.

This way:

- Development experience is nice
- CI does test the "dist" version
- tests now contains `import { … } from 'immutable'` instead of `import { … } from '../'`

**Review by conartist6 — APPROVED** [review]
Oh awesome.

**Review by Methuselah96 — APPROVED** [review]
Awesome, thanks! This will make debugging much easier.

**Comment by jdeniau** [comment]
🎉🎉

**Pull request merged**
